# Generated by Django 2.2.4 on 2019-08-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Ináctivo'), (1, 'Activo')], default=0),
        ),
    ]
