# Generated by Django 2.2.4 on 2019-08-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('town', '0002_auto_20190803_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Código')),
                ('name_region', models.CharField(max_length=100, verbose_name='Nombre')),
                ('town', models.ManyToManyField(to='town.Town', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
                'ordering': ['-name_region'],
            },
        ),
    ]
